cross_target_platform:
  - linux-64                            # [linux and x86_64]
  - linux-aarch64                       # [linux and aarch64]
  - linux-s390x                         # [linux and s390x]
  - osx-64                              # [osx and x86_64]
  - osx-arm64                           # [osx and arm64]
  - win-64                              # [win and x86_64]
GOOS:
  - linux                               # [linux]
  - darwin                              # [osx]
  - windows                             # [win]
GOARCH:
  - amd64                               # [x86_64]
  - arm64                               # [aarch64 or arm64]
  - s390x                               # [s390x]
go_variant_str:
  - cgo
  - nocgo
go_variant_ver:
  - 2.3.0
  - 2.2.0
cgo:
  - true
  - false
zip_keys:
  -
    - cross_target_platform
    - GOOS
    - GOARCH
  -
    - go_variant_str
    - go_variant_ver
    - cgo
